root = true

[secrets]
GREPTILE_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaHpjNXlyS2lKN3A5eGIrNmhyL2hEU0gvUVpmZ0hJZkhidjZBRnp0K0N3CitKSUI1NEs5VHdURDR4OTFPbHErWnpyVW1BcmpXYlo0YkFheDM2emNXN1UKLT4gJHdiP2J+JjEtZ3JlYXNlIHlkJCB7UiB5Y3JLKCBaM24Ka2E5Uk5PL3dvTk55QmlZb0tINTVDd0JuY05lalFDcU9tdkk1UFpHRmh0cXlSc2hPQkt4dklwUmkyMUJPejJWagp3ejl5VzJxcHhRUWF2cUNQMjF5M0hVR2o4MUo4YlZEWThMSGc2MDk5eGFiQ2JnCi0tLSBxZVVkMGFrQ3M4WG5xdlhRUmU1YUU3UUJHMjB2ekhTMDlkaUQ3eFRMNXRzCohzunpp/rg6ODBp8bCGGdnsVLpFqA2Yu3iIFudkbMi9" }
